version: "3"
services:

  speedtest:
    restart: unless-stopped
    build: 
      context: ./speedtest_cli
    environment:
      TEST_INTERVAL: 5
      INFLUXDB_USER: speedmonitor
      INFLUXDB_PASSWORD: speedpassword
      INFLUXDB_DATABASE: internetspeed
      INFLUXDB_HOST: influxdb
      INFLUXDB_PORT: 8086
    volumes: 
      - ./speedtest_data:/app/data
    depends_on:
      - influxdb

  influxdb:
    restart: unless-stopped
    image: influxdb:1.8
    environment:
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_ADMIN_PASSWORD: password
      INFLUXDB_DB: internetspeed
      INFLUXDB_USER: speedmonitor
      INFLUXDB_USER_PASSWORD: speedpassword
    volumes:
      - ./influxdb_data:/var/lib/influxdb
    expose:
      - "8086"
  
  grafana:
    restart: unless-stopped
    image: grafana/grafana:latest
    volumes:
      - ./grafana_data/data/grafana:/var/lib/grafana
    ports:
      - "3000:3000"
    depends_on:
      - influxdb
    